// Code generated by mfd-generator v0.4.5; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"unicode/utf8"
)

const (
	ErrEmptyValue = "empty"
	ErrMaxLength  = "len"
	ErrWrongValue = "value"
)

func (s Statistic) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(s.TgUserID) > 255 {
		errors[Columns.Statistic.TgUserID] = ErrMaxLength
	}

	if utf8.RuneCountInString(s.Exercise) > 255 {
		errors[Columns.Statistic.Exercise] = ErrMaxLength
	}

	return errors, len(errors) == 0
}
