// Code generated by mfd-generator v0.4.5; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"
)

var Columns = struct {
	Statistic struct {
		ID, TgUserID, Exercise, Value, Params, CreatedAt, StatusID string
	}
}{
	Statistic: struct {
		ID, TgUserID, Exercise, Value, Params, CreatedAt, StatusID string
	}{
		ID:        "statisticId",
		TgUserID:  "tgUserId",
		Exercise:  "exercise",
		Value:     "value",
		Params:    "params",
		CreatedAt: "createdAt",
		StatusID:  "statusId",
	},
}

var Tables = struct {
	Statistic struct {
		Name, Alias string
	}
}{
	Statistic: struct {
		Name, Alias string
	}{
		Name:  "statistics",
		Alias: "t",
	},
}

type Statistic struct {
	tableName struct{} `pg:"statistics,alias:t,discard_unknown_columns"`

	ID        int              `pg:"statisticId,pk"`
	TgUserID  int              `pg:"tgUserId,use_zero"`
	Exercise  string           `pg:"exercise,use_zero"`
	Value     float64          `pg:"value,use_zero"`
	Params    *StatisticParams `pg:"params"`
	CreatedAt time.Time        `pg:"createdAt,use_zero"`
	StatusID  int              `pg:"statusId,use_zero"`
}
