name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sport_statsrv
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'

    - uses: actions/checkout@v3

    - name: Prepare test db
      run: psql -d postgresql://postgres@localhost/sport_statsrv < schema.sql
      working-directory: ./docs/
      env:
        PGPASSWORD: postgres

    - name: Test
      run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'

    - name: Build
      run: go build -mod=vendor -o sportstat main.go
